### ISSUE TITLE
Discord link for save decrypter is invalid.

### ISSUE THREAD

**Issue by Seperest** [KiraTheReaper435/ff13-save-editor-software#1]
The link opens discord, but there's no channel and no invite.

**Comment by KiraTheReaper435** [comment]
Hello!

There is a discord invite in the post, just checked the link and it works. If you join the discord using the invite first and then use the link to go to the specified post, it should work.

Any issues contact me on discord @ kirathereaperuwu  and I can send it to you directly if needed :)
