### ISSUE TITLE
Dialogs looping when cancelling file selection

### ISSUE THREAD

**Issue by B01scout** [KiraTheReaper435/ff13-save-editor-software#4]
Clicking on "Open File", then cancelling the dialog shows the message "Select a Save." and reopens the file system dialog. Endlessly repeatable and traps the user.
Effectively the user cannot cancel this functions and close the program by normal means. I'm surprised this loophole has not been addressed yet.

![image](https://github.com/user-attachments/assets/af8c00fb-f531-4f3d-ae62-95445250e517)

**Comment by KiraTheReaper435** [comment]
Fixed, will post in release tonight. Appreciate you letting me know about it.
